# 5.16 List 2 Dimensi

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list. Penggambarannya seperti sebuah matrik. 

In [1]:
#============================================================
#Latihan mengenai list 2 dimensi
#Membuat Matriks dalam list 2 dimensi
#============================================================

# Dideklarasikan sebuah variabel 'matriks' yang berisi beberapa list angka yang membentuk matriks
matriks = [
    [-1, 0, 1, 2, 3, 4], #baris ke 0
    [5, 6, 7, 8, 9], #baris ke 1
    [10, 11, 12, 13], #baris ke 2
    [14, 15, 16, 17], #baris ke 3
]
#Begitu pula dengan kolom dengan kolom yang paling kiri adalah kolom ke-0, setelahnya adalah kolom ke-1, dan seterusnya
print (matriks)
#dilakukan perintah print untuk mencetak hasil

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Adapun output yang dihasilkan yaitu seperti vektor dalam vektor
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



[[-1, 0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13], [14, 15, 16, 17]]


In [4]:
#============================================================
#Memanggil matriks tertentu
#============================================================

#Kita akan memanggil matriks baris ke-3 
matriks [3]

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah seluruh elemen matriks baris ke-3
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


[14, 15, 16, 17]

In [7]:
#============================================================
#Memanggil anggota tertentu dalam list 2 dimensi
#============================================================

#Kita akan memanggil sebuah anggota matriks pada kolom dan baris tertentu
matriks [1][3]
#angka [1] menunjukkan baris
#angka [3] menunjukkan kolom

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah elemen matriks baris ke-2 kolom ke-5
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

8

In [10]:
#============================================================
#Mengganti salah satu elemen dalam list 2 dimensi
#============================================================

#Kita akan mengganti salah satu elemen dalam varibel matriks
#Misalnya kita akan mengganti elemen matriks baris ke-1 kolom ke-3 dengan angka 17
matriks [2][3] = 20
#dideklarasikan variabel beserta baris dan kolom yang ingin diganti serta sertakan pula angka penggantinya
# [2] menunjukkan baris
# [3] menunjukkan kolom
print (matriks [2][3])
#dilakukan perintah print untuk mencetak angka yang menjadi pengganti yaitu 17



20


In [11]:
#ketik kembali variabel untuk mencetak anggota list yang baru
matriks

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah elemen matriks dari baris ke-2 kolom ke-3 akan berubah menjadi 20
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

[[-1, 0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 20], [14, 15, 16, 17]]

In [12]:
#=================================================================
#Memanggil anggota tertentu dalam list 2 dimensi menggunakan for
#=================================================================

for baris in matriks :
    print (baris)
#gunakan perintah print, kemudian sistem akan mencetak baris dari setiap matriks
    for kolom in baris :
        print (kolom)
#gunakan perintah print maka sistem akan mencetak baris dalam bentuk kolom

[-1, 0, 1, 2, 3, 4]
-1
0
1
2
3
4
[5, 6, 7, 8, 9]
5
6
7
8
9
[10, 11, 12, 20]
10
11
12
20
[14, 15, 16, 17]
14
15
16
17


In [13]:
#Hal ini akan berbeda dengan
#akan berbeda dengan
for baris in matriks :
    print (baris)
#setelah seluruh baris akan diprint terlebih dahulu
#kemudian baru di print untuk kolomnya ( dan kolom yang diprint hanya yang paling akhir atau cetakan terakhir)
for kolom in baris :
        print (kolom)
        
#output yang dihasilkan adalah seluruh baris dalam matriks dan kolom daari baris trakhir matriks

[-1, 0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 20]
[14, 15, 16, 17]
14
15
16
17


In [17]:
#====================================================================================
#List 2 dimensi dengan menggunakan tipe data string
#List 2 dimensi tidak hanya bisa dilakukan pada tepe data integer atau numerik
#Namun, juga dapat digunakan pada tipe data string
#===================================================================================
#deklarasikan variabel dengan anggota list 2 dimensi
#ingat untuk menyertakan tanda '' atau " " untuk setiap elemen karena jika tidak ada, maka sistem akan membaca sebagai variabel sehingga output akan error
nama_teman = [
    ['Eka', 'Gek Ayu', 'Gita', 'Kendran'], #baris ke-0
    ['Adina', 'Leo', 'Atmaja', 'Indry', 'Rika'], #baris ke-1
    ['Mitha', 'Praja', 'Utik'], #baris ke-2
]
   
print (nama_teman)
#cetak variabel

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Adapun output yang dihasilkan yaitu seperti vektor dalam vektor 
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

[['Eka', 'Gek Ayu', 'Gita', 'Kendran'], ['Adina', 'Leo', 'Atmaja', 'Indry', 'Rika'], ['Mitha', 'Praja', 'Utik']]


In [19]:
#Pada list 2 dimensi tipe data string dapat dilakukan pula pemanggilan elemen-elemen dari baris tertentu
nama_teman [2]

#akan dicetak elemen dari baris ke-2

['Mitha', 'Praja', 'Utik']

In [21]:
#Dapat pula dilakukan pemanggilan elemen dari baris dan kolom tertentu
nama_teman [1][0]

#akan dicetak elemen dari baris ke-1 kolom ke-0

'Adina'

In [22]:
#Dapat pula mengganti salah satu elemen dalam list 2 dimensi
nama_teman [1][3] = 'Suta'
print (nama_teman [1][3])

Suta


In [23]:
#panggil kembali variabel nama_teman
nama_teman
#Output yang dihasilkan adalah elemen dari baris ke-1 dan kolom ke-3 yaitu 'Indry' akan berubah menjadi 'Suta'

[['Eka', 'Gek Ayu', 'Gita', 'Kendran'],
 ['Adina', 'Leo', 'Atmaja', 'Suta', 'Rika'],
 ['Mitha', 'Praja', 'Utik']]

# 5.17 Tuples

Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan jika datanya masih ingin dimanipulasi kedepannya, gunakan list.

In [25]:
#============================================================
#Latihan mengenai tuples
#============================================================

#dideklarasikan suatu variabel bilangan dengan elemen-elemen sebagai berikut
bilangan = (1, 3, 5, 7, 9, 11)

In [28]:
#============================================================
#Latihan mengenai tuples
#Mencetak anggota dengan index tertentu dalam tuples
#============================================================

print (bilangan [4])
#angka [4] mengartikan index ke-4 dari anggota variabel 'bilangan' yang ingin dicetak

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah elemen dari variabel bilangan index ke-4
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

9


In [29]:
#============================================================
#Mencetak anggota dengan index tertentu dalam tuples
#============================================================

print (bilangan [1 : 3])

#angka sebelum : yaitu 1 berarti dimulainya indeks yang akan dicetak yaitu indeks ke 1
# angka setelah : yaitu 3 berarti angka berakhirnya dari angka yang akan dicetak. Namun, indeks ke-3 tidak akan dicetak dalam output
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah elemen dari variabel bilangan index ke-1 sampai dengan angka  sebelum indeks ke-3
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

(3, 5)


In [31]:
#=======================================================================================
#Latihan mengenai tuples
#Mencetak anggota dengan index tertentu dalam tuples dengan menggunakan fungsi 'for'
#======================================================================================

for prima in bilangan [1:3] :
    print (prima)

3
5


In [32]:
#============================================================
#Latihan mengenai tuple
#Tuples tidak bisa diganti
#Apabila elemen dalam tuples diganti,akan menghasilkan error
#============================================================
bilangan [0] = 8

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah error karena tuples tidak bisa diganti
#agar bisa diganti gunakan list
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

TypeError: 'tuple' object does not support item assignment

In [33]:
#============================================================
#Latihan mengenai tuple
#Menghitung banyaknya suatu anggota yang sama dalam tuples
#============================================================

#dengan menggunakan ".count" kita dapat menghitung banyaknya suatu bilangan dalam variabel tuples
bilangan.count (5)
#disini kita ingin mengetahui banyaknya bilangan 5 dalam variabel "bilangan"



1

In [34]:
#============================================================
#Latihan mengenai tuple
#Mengetahui letak indeks suatu elemen dalam tuples
#============================================================

#dengan menggunakan ".index" kita dapat mengetahui indeks dan letak suatu elemen dalam variabel tuples
bilangan.index(5)
#kita ingin mengetahui angka 5 terletak pada indeks berapa pada variabel bilangan

2

# 5.18 Dictionaries

Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan data yang bersumber dari orang tersebut.

In [35]:
#============================================================
#Latihan mengenai Dictionaries
#Mendeklarasikan suatu data
#============================================================

#Dideklarasikan suatu variabel bernama "data_saya" yang berisi data yang terkait dengan satu sama lain
data_saya = {
    "Nama" : "Eka Martini",
    "Usia" : 19,
    "Apakah_mahasiswa" : False,
    "Apakah_hindu" : True,
}

In [ ]:
#============================================================
#Latihan mengenai Dictionaries
#Menampilkan nilai yang terdapat pada dictionaries
#============================================================

print (data_saya ['Nama'])
#Kode akan mengambil nilai dari karakter 'Nama' dalam variabel. Kemudian, nilai tersebut akan dicetak dengan menggunakan perintah print

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah string "Eka Martini"
#karena nilai dari karakter 'Nama' adalah "Eka Martini"
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

In [36]:
print (data_saya ['nama'])
#Kode ini akan menghasilkan error karena dalam variabel data_saya tidak terdapat karakter 'nama'

KeyError: 'nama'

In [37]:
#============================================================
#Latihan mengenai Dictionaries
#Menggunakan method 'get'
#Metode get digunakan untuk mengambil nilai dari sebuah kata kunci dalam dictionary
#============================================================

print (data_saya.get('Nama'))
#Kita ingin menampilkan nilai dari 'Nama' yang terdapat dalam dictionaries variabel data_saya.

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah string "Eka Martini"
#karena nilai dari karakter kata kunci 'Nama' adalah "Eka Martini"
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Eka Martini


In [ ]:
#============================================================
#Latihan mengenai Dictionaries
#Menggunakan method 'get'
#============================================================
#Dalam metode get, jika kata kunci tidak ditemukan, maka tidak akan menghasilkan error
#Namun, akan menghasilkan nilai default yang disebut 'None'

print (data_saya.get ('tanggal_lahir'))

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Output yang dihasilkan adalah nilai default (None) karena kata kunci tanggal lahir tidak ada dalam dictionaries variabel data_saya
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


In [38]:
#============================================================
#Latihan mengenai Dictionaries
#Menambahkan kata kunci baru dalam dictionaries
#============================================================

data_saya ['Line'] = 'ekamartini23'
#Kode diatas akan menambahkan nilai dari kata kunci baru pada dictionaries data_saya


In [39]:
#Apabila kita print atau cetak kembali variabel data saya, maka akan menambah nilai dari kata kunci dalam dictionaries
print (data_saya)

{'Nama': 'Eka Martini', 'Usia': 19, 'Apakah_mahasiswa': False, 'Apakah_hindu': True, 'Line': 'ekamartini23'}


#### Program menggunakan DIctionaries

In [49]:
# Minta input dari pengguna
nama = input("Masukkan Nama Anda: ")
usia = int(input("Masukkan Usia Anda: ")) #input usia diubah menjadi tipe data integer
pekerjaan = input("Masukkan Pekerjaan Anda: ")
#digunakan perintah 'input'

# Buat dictionary dari data pengguna
data_orang = {
    "Nama": nama,
    "Usia": usia,
    "Pekerjaan": pekerjaan
}
#setelah mendapatkan input dari user, dibuat sebuah dictionary dengan kata kunci yang disesuaikan 

# Tampilkan data pengguna
print("Data Anda:")
for key, value in data_orang.items():
    print(key + ":", value)
    
#digunakan for loop dan fungsi items pada dictionary
#setiap nilai kata kunci akan ditampilkan dengan menggunakan perintah print


Masukkan Nama Anda: Eka
Masukkan Usia Anda: 19
Masukkan Pekerjaan Anda: Mahasiswa
Data Anda:
Nama: Eka
Usia: 19
Pekerjaan: Mahasiswa


# 5.19 Fungsi dalam Python

Pada dasarnya fungsi dibentuk untuk menghidari pengulangan pembuatan program secara manual dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang
kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat, setiap fungsi tersebut dibutuhkan tinggal kita panggil.

In [2]:
#============================================================
#Latihan mengenai Fungsi dalam Python
#============================================================
#Berikut merupakan sebuah fungsi Python yang menerima 2 parameter yaitu first name dan last name serta akan mencetak nama lengkap dari kedua variabel tersebut

def full_name(first_name,last_name) :
#didefinisikan sebuah fungsi full name yang menerima 2 parameter yaitu first_name dan last_name
    print ("Nama lengkap dia adalah",first_name,last_name)
#akan dicetak sebuah pesan yang terdiri dari string "Nama lengkap dia adalah" kemudian diikuti dengan kedua parameter first name dan last name tadi

In [4]:
#============================================================
#Latihan mengenai Fungsi dalam Python
#Memanggil fungsi yang telah didefisnisikan sebelumnya
#============================================================
first_name = input ("Masukkan nama depan : ")
#meminta user untuk memasukkan nama depan
#kemudian, input tersebut akan disimpan dalam variabel first_name
last_name = input ("Masukkan nama belakang : ")
#meminta user untuk memasukkan nama belakan
#kemudian, input tersebut akan disimpan dalam variabel last_name
full_name (first_name,last_name)
#memanggil fungsi full_name dengan memberikan first name dan last_name sebagai argumen

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Dengan memasukkan nama depan dan nama belakang user pada saat program di-run, fungsi full_name akan mencetak nama depan dan nama belakang yang telah dimasukkan oleh user
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


Masukkan nama depan : Jerome
Masukkan nama belakang : Polin
Nama lengkap dia adalah Jerome Polin


## 5.19.1 Tugas Fungsi dalam Python

Ada dua jenis tugas fungsi pada Python yaitu:
- Menjalankan perintah.
- Menampilkan hasil perhitungan

In [5]:
#============================================================
#Latihan mengenai Tugas Fungsi dalam Python
#============================================================

def waktu_tempuh(jarak, kecepatan):
#didefinisikan suatu variabel waktu_tempuh yang akan berisi jarak dan kecepatan
    waktu_jam = jarak / kecepatan
#dimasukkan rumus mencari waktu dengan satuan jam yaitu jarak dibagi dengan kecepatan
    waktu_menit = waktu_jam * 60
#Kemudian, akan dicari waktu tempuh dalam satuan menit dengan mengalikan waktu tempuh dalam jem dengan 60
    print("Waktu tempuh adalah :", waktu_menit, "menit")
#Selanjutnya akan doi-print teks "Waktu tempuh adalah : .... menit "

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#Pada saat pemanggilan fungsi, jarak dan kecepatan disediakan sebagai argumen dan hasilnya akan langsung di-print
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


In [35]:
#didefinisikan waktu sampai yakni jarak dan kecepatan
def waktu_sampai(jarak,kecepatan):
  #didefinisikan untuk waktu yakni dengan rumus jarak dibagi kecepatan
  waktu = jarak/kecepatan
  #selanjutnya akan dikembalikan untuk nilai waktu menggunakan fungsi return
  return waktu

In [6]:
#============================================================
#Latihan mengenai Tugas Fungsi dalam Python
#Pemanggilan fungsi
#============================================================
waktu_tempuh (80,20)
#akan dipanggil fungsi waktu_tempuh dengan argumen 80 dan 20
#selanjutnya fungsi akan menghitung waktu tempuh dengan membagi jarak 80 dengan kecepatan 20
#setelah diperleh hasil yaitu 4, angka 4 akan diiterasi kembali dengan fungsi yaitu dengan dikalikan 60 untuk mendapatkan hasil dalam satuan menit
#selanjutnya, hasilnya akan dicetak atau diprint ke layar yaitu 4*60 = 240,0

Waktu tempuh adalah: 240.0 menit


In [36]:
waktu_sampai (80,20)
#didefinisikan waktu sampai dengan jarak 80 dan kecepatan 20

4.0

# 5.20 Numpy

Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi.

In [3]:
#============================================================
#Latihan mengenai Numpy atau numeric Python
#Pemanggilan library numpy
#============================================================
#Pemanggilan library NumPy dilakukan karena NumPy menyediakan berbagai fitur dan agar terbaca oleh sistem
#berikut merupakan kode untuk pemanggilan library numpy
import numpy as np

## 5.20.1 Perintah Dasar pada Numpy

In [5]:
#============================================================
#Latihan mengenai Perintah Dasar pada Numpy atau numeric Python
#============================================================

#dideklarasikan sebuah data array dengan matriks berordo 4x4
l = np.array ([[1,2,3,4], [3,5,7,9], [0,-1,-2,-3], [10,15,20,25]])
#dilakukan dengan mengimpor library Numpy yang telah diinisialkan dengan 'np' 
#serta membuat array dengan fungsi "np.array" untuk disimpan dalam variabel l
print (l)
#dilakukan pencetakan variabel l yang memiliki 4 baris dan 4 kolom dan berisi angka-angka yang telah dideklarasikan

[[ 1  2  3  4]
 [ 3  5  7  9]
 [ 0 -1 -2 -3]
 [10 15 20 25]]


In [6]:
#dideklarasikan sebuah data array dengan matriks berordo 2x4
m = np.array ([[9,8,7,6], [0,1,2,3]])
print (m)

[[9 8 7 6]
 [0 1 2 3]]


In [8]:
#============================================================
#Latihan mengenai Numpy atau numeric Python
#data matriks dengan menggunakan banyak kurung siku
#============================================================
n = np.array ([[[0,2,4,6], [2,3,4,5]],
              [[5,6,4,7], [4,5,9,0]],
              [[1,8,9,5], [1,4,6,9,]]])
#akan membuat array 3 dimensi yang terdiri dari 3 sub
#setiap sub akan memiliki 2 baris dan 4 kolom matriks 
#kemudian disimpan dalam variabel n
print (n)
#dilakukan pencetakan nilai-nilai n

[[[0 2 4 6]
  [2 3 4 5]]

 [[5 6 4 7]
  [4 5 9 0]]

 [[1 8 9 5]
  [1 4 6 9]]]


In [9]:
#============================================================
#Latihan mengenai Numpy atau numeric Python
#fitur .ndim
#============================================================
l.ndim
#digunakan untuk mengetahui jumlah dimensi dari sebuah array dalam Numpy
#sehingga sistem akan mencetak dimensi matriks dari array tersebut

2

In [10]:
m.ndim

2

In [11]:
n.ndim

3

In [12]:
#============================================================
#Latihan mengenai Numpy atau numeric Python
#fitur .shape
#============================================================
l.shape
#digunakan untuk mengetahui dimensi dari matris tersebut yang berisi banyaknya elemen dalam matris tersebut
#pada kasus ini yang dicetak adalah (4,4) dimana array l memiliki 4 elemen di dimensi pertama dan 4 elemen pada dimensi kedua

(4, 4)

In [13]:
m.shape

(2, 4)

In [14]:
n.shape

(3, 2, 4)

## 5.20.2 Memanggil Anggota, Kolom, dan Baris dengan Numpy

In [3]:
import numpy as np

In [4]:
#============================================================
#Latihan mengenai Memanggil Anggota, Kolom, dan Baris dengan Numpy atau numeric Python
#============================================================
#dideklarasikan sebuah data array dengan matriks berordo 4x4
l = np.array ([[1,2,3,4], [3,5,7,9], [0,-1,-2,-3], [10,15,20,25]])
#dilakukan dengan mengimpor library Numpy yang telah diinisialkan dengan 'np' 
#serta membuat array dengan fungsi "np.array" untuk disimpan dalam variabel l
print (l)

[[ 1  2  3  4]
 [ 3  5  7  9]
 [ 0 -1 -2 -3]
 [10 15 20 25]]


In [7]:
#============================================================
#Latihan mengenai Memanggil Anggota, Kolom, dan Baris dengan Numpy atau numeric Python
#Mengambil elemen dari suatu matriks (1)
#============================================================
l [1,3]
#Kode ini akan menghasilkan output elemen dari bari ke 1 dan kolom ke-3 pada matriks
#angka 1 melambngkan baris, dan angka 3 melambangkan kolom

9

In [8]:
#============================================================
#Latihan mengenai Memanggil Anggota, Kolom, dan Baris dengan Numpy atau numeric Python
#Mengambil elemen dari suatu matriks (2)
#============================================================
l [1, :]
#Kode ini akan mengambil semua elemen yang berada pada baris ke-1\
# ':' digunakan untuk menunjukkan bahwa ingin mengambil seluruh elemen dari baris ke-1

array([3, 5, 7, 9])

In [10]:
#============================================================
#Latihan mengenai Memanggil Anggota, Kolom, dan Baris dengan Numpy atau numeric Python
#Mengambil elemen dari suatu matriks (3)
#============================================================
l[:,3]
#Kode ini akan mengambil semua elemen pada kolom ke-3
# ':' digunakan untuk menunjukkan bahwa kita kanan mengambil semua elemen pada kolom ke-3

array([ 4,  9, -3, 25])

In [11]:
#============================================================
#Latihan mengenai Memanggil Anggota, Kolom, dan Baris dengan Numpy atau numeric Python
#Mengambil elemen dari suatu matriks (4)
#============================================================
l[0, 1 : 3]
#Kode ini akan memberikan output berupa elemen pada baris ke 0 dan kolom ke-1 hingga kolom ke-2 pada matriks
# 0 menunjukkan baris
# 1 : 3 menunjukkan indeks dari elemen matriks yang akan diambil

array([2, 3])

## 5.20.3 Matriks pada Numpy

In [1]:
import numpy as np

In [2]:
#============================================================
#Latihan mengenai Matriks pada Numpy
#Fungsi .ones
#============================================================

#Akan dibuat matriks dengan ukuran 2 baris dan 3 kolom dimana semua elemennya adalah 1
np.ones ((2,3))
#fungsi (.ones) ini digunakan untuk memmbuat matriks berordo tertentu dengan semua elemennya memiliki nilai 1
# 2 menunjukkan baris
# 3 menunjukkan kolom

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#============================================================
#Latihan mengenai Matriks pada Numpy
#Fungsi .ones (2)
#============================================================
np.ones ((2,4,5))
#kode ini akan membuat matriks 2 blok dengan masing-masing blok memiliki 4 baris dan 5 kolom serta semua elemenya bernilai 1

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [4]:
#============================================================
#Latihan mengenai Matriks pada Numpy
#Fungsi .zeros
#============================================================

#Akan dibuat matriks dengan ukuran 3 baris dan 2 kolom dimana semya elemennya adalah 0
np.zeros((3,2))
#fungsi (.zeros) ini digunakan untuk memmbuat matriks berordo tertentu dengan semua elemennya memiliki nilai 0
# 3 menunjukkan baris
# 2 menunjukkan kolom

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
#============================================================
#Latihan mengenai Matriks pada Numpy
#Fungsi .identity
#============================================================
np.identity(4)
#Fungsi .identity digunakan untuk membuat sebuah matriks identitas 
#matriks identitas adalah matriks dimans semua elemen di diagonal utamanya adalah 1 sedangkan elemen lainnya bernilai 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#============================================================
#Latihan mengenai Matriks pada Numpy
#Fungsi .full
#============================================================

#Fungsi (.full) digunakan untuk membuat sebuah matriks dengan ukuran tertentu 
#semua elemen dalam matriks telah ditentukan melalui kode tersebut
np.full ((3,2),9)
#kode diatas akan menghasilkan matriks dengan ordo 3x2 dengan semua elemenya bernilai 9


array([[9, 9],
       [9, 9],
       [9, 9]])

In [9]:
#============================================================
#Latihan mengenai Matriks pada Numpy
#Fungsi .random.rand
#============================================================

#fungsi (.random.rand) digunakan untuk menghasilkan nilai acak dengan distribusi yang seragam antara 0 sampai 1
np.random.rand (4,3)
#kode diatas akan menghasilkan matriks 2 dimensi dengan ordo 4x3 dimana elemennya adalah nilai acak yang terdistribusi seragam antara 0 samapi 1

array([[0.12637989, 0.42815669, 0.7542596 ],
       [0.89315251, 0.30008057, 0.41764903],
       [0.95077182, 0.16332082, 0.53637502],
       [0.28718985, 0.92161575, 0.15110081]])

In [10]:
#============================================================
#Latihan mengenai Matriks pada Numpy
#Fungsi .random.randint dengan size
#============================================================

#fungsi (.random.randint) digunakan untuk menghasilkan matriks dengan elemennya adalah nilai acak di antara 2 nilai yang telah ditentukan
np.random.randint (1,10,size = (3,4))
#telah ditentukan batas bawah adalah 1 dan batas atasnya adalah 0
#ukuran dari matriks adalah 3x4
#elemen-elemen yang akan menjadi output adalah bilangan bulat antara 1-10 yang dijadikan matriks dan disusun acak

array([[4, 3, 1, 8],
       [7, 6, 9, 6],
       [6, 3, 7, 9]])

## 5.20.4 Copy pada Numpy

In [11]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [9]:
#============================================================
#Latihan mengenai Copy pada Numpy
#============================================================
#pada python, ketika sebuah objek dimasukkan dalam variabel, variabel itu tidak akan menyimpan dari nilai objek tersebut. 
#melainkan hanya menunjuk memori dimana objek tersebut disimpan

b = a
#variabel b hanya menunjuk ke alamat memori yang sama dengan a sehingga variabel a dan b akan menunjuk dalam memori
print (b)
#dilakukan pencetakan dan hasil yang diberikan adalah elemen dari a dan b adalah sama

[1 2 3 4]


In [14]:
#============================================================
#Latihan mengenai Copy pada Numpy
#Mengubah elemen
#============================================================
b [0] = 10
#Variabel b menunjuk pada elemen yang sama dengan variabel a.
#kode ini akan merubah baris ke-0 dan kolom ke- 0 pada matriks dengan variabel b menjadi 10
print (b)
#dilakukan pencetakan matriks yang telah diubah


[10  2  3  4]


In [15]:
#Perubahan diatas juga terlihat pada matriks yang berada di variabel a
#Jika kita mencetak matriks a setelah mengubah elemen baris ke-0 dan kolomke-0 dari matriks b, maka elemen baris ke-0 dan kolom ke-0 dari a juga akan berubah menjadi 10
print (a)

[10  2  3  4]


In [16]:
#dideklarasikan variabel baru dengan anggota sebagai berikut
c = np.array ([1,2,3,4])
print (c)

[1 2 3 4]


In [17]:
#============================================================
#Latihan mengenai Copy pada Numpy
#Membuat salinan dengan kode c.copy()
#============================================================
d = c.copy()
#kode diatas akan membuat salinan dari variabel c dan menempel salinan tersebut ke varianel d
#sehingga elemen dari c dan d akan sama
#tetapi, perubahan yang dilakukan pada variabel d tidak akan mempengaruhi variabel c
print (d)

[1 2 3 4]


In [20]:
d [0] =10
#Variabel d menunjuk pada elemen yang sama dengan variabel c.
#kode ini akan merubah baris ke-0 dan kolom ke- 0 pada matriks dengan variabel d menjadi 10
print (d)

[10  2  3  4]


In [21]:
#tetapi, perubahan yang dilakukan pada variabel d tidak akan mempengaruhi variabel c
#sehingga, ketika kita mencetak c, maka elemen baris ke-0 dan kolom ke-0 tidak akan berubah menjadi 10
print (c)

[1 2 3 4]


## 5.20.5 Operasi Matematika pada Numpy

In [3]:
import numpy as np

In [8]:
#============================================================
#Latihan mengenai Operasi Matematika pada Numpy
#Operasi dasar pada matematika
#============================================================
a+5
#kode diatas akan menambahkan setiap elemen dari matriks yang memiliki variabel a dengan 5
#sehingga output yang dihasilkan adalah matriks baru setelah seluruh elemen pada matriks a ditmbahkan 5

array([6, 7, 8, 9])

In [10]:
#operasi pengurangan
a-3

array([-2, -1,  0,  1])

In [11]:
#operasi pembagian
a/2

array([0.5, 1. , 1.5, 2. ])

In [12]:
#operasi perkalian
a*10

array([10, 20, 30, 40])

In [13]:
#dideklarasikan variabel baru dengan elemen-elemen sebagai berikut
b = np.array ([2,3,5,7])
print (b)

[2 3 5 7]


In [14]:
a-b
#kode diatas akan melakukan operasi pengurangan elemen per elemen antara matriks a dan b
#namun, harus dipastikan bahwa matriks dari a dan b berukuran sama

array([-1, -1, -2, -3])

In [17]:
b*a
#hal tersebut juga berlaku pada operasi perkalian

array([   2,    9,  125, 2401], dtype=int32)

In [18]:
#============================================================
#Latihan mengenai Operasi Matematika pada Numpy
#Operasi Trigonometri
#============================================================
np.cos (a)
#kode diatas akan menghitung nilai cos dari setiap elemen pada matriks a
#output yang dihasilkan adalah matriks yang menjadi hasil dari cos tiap elemen di a

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [20]:
#begitu juga dengan operasi tangen
np.tan (a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [19]:

np.tanh (a)
#kode diatas akan menghitung nilai dari tangen hiperbolik dalam setiap elemen matriks a
#output yang dihasilkan adalah matriks baru yang menjadi hasil dari tangen hiperboli dari setiap elemen di a

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 ])

In [21]:
#berikut adalah kode untuk mencari cos hiperbolik dari matriks a
np.cosh (a)

array([ 1.54308063,  3.76219569, 10.067662  , 27.30823284])

In [22]:
#============================================================
#Latihan mengenai Operasi Matematika pada Numpy
#Operasi Akar kuadrat
#============================================================
np.sqrt (a)
#kode diatas akan menghitung akar kuadrat dari setiap elemen dalam matriks a
#output yang dihasilkan adalah matriks baru yang berisi hasil dari akar kuadrat matriks a

array([1.        , 1.41421356, 1.73205081, 2.        ])

## 5.20.6 Perkalian Matriks pada Numpy

In [15]:
import numpy as np

In [16]:
#dideklarasikan matriks d dengan elemen-elemen sebagai berikut
d = np.array([[5,6,7,8],[8,9,10,11]])
print (d)

[[ 5  6  7  8]
 [ 8  9 10 11]]


In [18]:
#dideklarasikan pula matriks e dengan elemen-elemen sebagai berikut
e = np.array ([[0,4,8,0], [1,4,5,6]])
print (e)

[[0 4 8 0]
 [1 4 5 6]]


In [30]:
#============================================================
#Latihan mengenai Operasi Perkalian pada Matriks
#============================================================

k = d*e
#kode diatas akan mengalikan antara matriks d dan e
#hasil dari perkalian tersebut akan disimpan dalam variabel k
#perlu diingat bahwa ordo atau ukuran dari matriks harus sama
print (k)
#dilakukan pencetakan antara perkalian matriks d dan e

[[ 0 24 56  0]
 [ 8 36 50 66]]


In [26]:
#dideklarasikan matriks baru yaitu s dengan elemen sebagai berikut
s = np.array([[1,2],[4,5],[6,8],[9,7]])
print (s)

[[1 2]
 [4 5]
 [6 8]
 [9 7]]


In [27]:
#============================================================
#Latihan mengenai Operasi Perkalian pada Matriks
#fungsi .matmul
#============================================================
#fungsi .matmul () merupakan fungsi yang digunakan untuk melakukan perkalian matriks pada numpy
b = np.matmul (d,s)
#kode diatas akan melalkukan operasi perkalian matriks d dan s
#hasil perkalian akan disimpan dalam variabel b 
print (b)
#kemudian hasil perkalian dicetak dengan perintah print

[[143 152]
 [203 218]]


## 5.20.7 Min, Max, dan Sum pada Numpy

In [2]:
import numpy as np

In [31]:
#dideklarasikan matriks dengan variabel v dengan elemen-elemen yang telah ditentukan
v = np.array ([[1,4,5,6],
              [5,9,8,0],
              [10,13,15,16]])
print (v)

[[ 1  4  5  6]
 [ 5  9  8  0]
 [10 13 15 16]]


In [7]:
#============================================================
#Latihan mengenai Nilai Min pada Matriks
#============================================================
z = np.min (v)
#fungsi .min() digunakan untuk mencari nilai minimum dari matriks v
#nilai minimum tersebut akan dicetak ke dalam variabel z
print (z)
#nilai z dicetak dengan perintah print

0


In [32]:
#============================================================
#Latihan mengenai nilai Min pada Matriks
#mencari nilai min dengan axis
#============================================================
s = np.min (v, axis=0)
#akan dilakukan perhitungan nilai minimum dari setiap kolom pada matriks v 
#ditambahkan sebuah parameter yaitu axis = 0 yang menandakan bahwa perhitungan dilakukan untuk setiap kolom
#hasilnya adalah matriks dengan jumlah baris 1 yang berisi nilai minimum dari setiap kolom pada matriks v
#hasil tersebut akan disimpan dalam variabel s
print (s)
#hasil akan dicetak dengan menggunakan perintah print

[1 4 5 0]


In [11]:
#============================================================
#Latihan mengenai nilai Max pada Matriks
#============================================================
f = np.max (v)
#fungsi .max() digunakan untuk mencari nilai maksimum dari matriks v
#nilai maksimum tersebut akan dicetak ke dalam variabel f
print (f)
#akan dicetak variabel f dengan perintah print

16


In [12]:
#============================================================
#Latihan mengenai operasi Max pada Matriks
#menghitung nilai max dengan axis
#============================================================
g = np.max (v, axis = 1)
#kode diatas akan mencari nilai maksimum dari setiap baris dalam variabel v
#argumen axis =1 mengartikan bahwa perhitungan nilai maksimum dilakukan per baris
#hasilnya akan menjadi matriks dengan elemen-elemen nilai maksimum dari setiap baris pada matriks p
#hasil tersebut akan disimpan dalam variabel g
print (g)
#variabel g akan dicetak dengan perintah print

[ 6  9 16]


In [13]:
#============================================================
#Latihan mengenai Sum pada Matriks
#menghitung nilai sum
#============================================================
t = np.sum (v)
#fungsi .sum() adalah fungsi yang digunakan untuk menghitung jumlah seluruh elemen yang terdapat pada variabel
#dalam kode ini, sistem akan menjumlahkan seluruh elemen yang berada dalam matriks v
#hasil tersebut akan disimpan dalam variabel t
print (t)
#Kemudian, variabel t dicetak dengan menggunakan perintah print yang menampilkan hasil penjumlahan pada array v

92


In [14]:
#============================================================
#Latihan mengenai Sum pada Matriks
#menghitung nilai sum dengan parameter axis
#============================================================
u = np.sum (v, axis = 0)
#kode diatas akan menjumlahkan seluruh elemen pada matriks v
#dengan menggunakan parameter axis = 0, sistem akan melakukan penjumlahan pada setiap kolom dari matriks v
#hasilnya adalah sebuah matriks yang berisi elemen-elemen hasil penjumlahan dari setiap elemen pada kolom matriks v
#hasil tersebut disimpan dalam variabel u
print (u)
#kemudian, hasil dicetak dengan menggunakan perintah print

[16 26 28 22]
